### ISSUE TITLE
Create Forest Zone sketch

### ISSUE THREAD

**Issue by bdickason** [stormsword/stormsword#6]
Simple sketch to help provide some idea of what the structure of the forest zone will look like.

Can be super low-fidelity and we'll work together to turn it into a tilemap.

Forest Zone basics: https://github.com/bdickason/stormsword/wiki/Level-1---Forest---Boss---Mob-mechanics

**Comment by ayrez** [comment]
Oh shit you’re back?

**Comment by bdickason** [comment]
Just noodlin on something :) We'll see where it goes.
